Eww

diff --git a/.github/workflows/starforge.yaml b/.github/workflows/starforge.yaml
--- a/.github/workflows/starforge.yaml
+++ b/.github/workflows/starforge.yaml
@@ -67,23 +67,25 @@ jobs:
       continue-on-error: true
     - name: List wheelhouse
       id: wheelhouse
-      run: ls -R "wheelhouse/" && echo "::set-output name=wheelhouse_exists::true" || echo "::set-output name=wheelhouse_exists::false"
+      run: ls -R "wheelhouse/" && echo "::set-output name=exists::true" || echo "::set-output name=exists::false"
     - uses: actions/setup-python@v2
-      if: ${{ steps.wheelhouse.outputs.wheelhouse_exists }}
+      # FIXME: why doesn't this work? it is always evaluating to true
+      #if: ${{ steps.wheelhouse.outputs.exists }}
       with:
         python-version: 3.9
     - name: Setup deploy environment
-      if: ${{ steps.wheelhouse.outputs.wheelhouse_exists }}
-      run: python3 -m venv ./venv && ./venv/bin/pip install "$S3PYPI" "$S3PYPI_ROOT_INDEX"
+      #if: ${{ steps.wheelhouse.outputs.exists }}
+      # Not using || here because it would mask venv/pip failures
+      run: 'if [ -d "wheelhouse/" ]; then python3 -m venv ./venv && ./venv/bin/pip install "$S3PYPI" "$S3PYPI_ROOT_INDEX"; fi'
     - name: Deploy wheels
-      if: ${{ steps.wheelhouse.outputs.wheelhouse_exists }}
-      run: ./venv/bin/s3pypi --bucket "$S3_BUCKET" --dist-path "./wheelhouse" --region "$S3_REGION" --force
+      if: ${{ steps.wheelhouse.outputs.exists }}
+      run: 'if [ -d "wheelhouse/" ]; then ./venv/bin/s3pypi --bucket "$S3_BUCKET" --dist-path "./wheelhouse" --region "$S3_REGION" --force; fi'
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     - name: Update root index page
-      if: ${{ steps.wheelhouse.outputs.wheelhouse_exists }}
-      run: ./venv/bin/s3pypi-root-index --bucket "$S3_BUCKET" --region "$S3_REGION"
+      if: ${{ steps.wheelhouse.outputs.exists }}
+      run: 'if [ -d "wheelhouse/" ]; then ./venv/bin/s3pypi-root-index --bucket "$S3_BUCKET" --region "$S3_REGION"; fi'
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
